CREATE DATABASE healthcare_retail;
USE healthcare_retail;
				# detect data types 
UPDATE customers_data
SET signup_date = STR_TO_DATE(signup_date, '%m/%d/%Y');
ALTER TABLE customers_data
MODIFY COLUMN signup_date DATE;
update employees 
set hire_date =str_to_date(hire_date,'%m/%d/%Y');
alter table employees 
modify column hire_date date ;
update products
set created_at =str_to_date(created_at,'%m/%d/%Y');
alter table products
modify column expiry_date date ;
alter table products
modify column created_at date ;
describe sales_data ;
update sales_data
set sale_date =str_to_date( sale_date,'%m/%d/%Y');
alter table sales_data
modify column sale_date date ;
describe stock_data ;
update stock_data
set expiry_date =str_to_date(expiry_date,'%m/%d/%Y'),
 received_date =str_to_date(received_date,'%m/%d/%Y') ;
alter table stock_data
modify column expiry_date date ;
alter table stock_data
modify column received_date date ;
update stock_data
set last_restocked =str_to_date(last_restocked,'%m/%d/%Y');
alter table stock_data
modify column last_restocked date ;
DESCRIBE sales_data;
						#update total amount
   UPDATE sales_data s
INNER JOIN products p 
    ON s.product_id = p.product_id
SET s.total_amount = (s.quantity * p.unit_price) - s.discount;


			#Sales Performance: Which store generated the highest total revenue in the last 12 months?
select store_id , sum(total_amount)as total_revenue from sales_data
where sale_date between date_sub(curdate(), interval 12 month) and curdate()
group by store_id 
order by total_revenue desc
limit 1;

			#List all products currently in stock where the stock_level is below 20 units.
select distinct p.product_id ,p.product_name , s.quantity from products p
inner join stock_data s on p.product_id=s.product_id
where  s.quantity <20;

			#Inventory Health:Category Analysis: What is the total profit (Revenue - Cost) generated by the 'Pharmaceuticals' category?
select * from sales_data ;
select c.category_name , sum(s.total_amount - s.cost_amount)
 as total_profit
from  sales_data s
inner join products p on s.product_id=p.product_id
inner join categories_data c  on p.category_id=c.category_id
where c.category_name = 'Pharmaceuticals'
group by c.category_name;

			#Employee Efficiency: Which employee has processed the highest number of individual sales transactions? 
Select e.employee_id , e.employee_name,Count(s.employee_id)as 
High_sales_transaction from employees e 
Inner join sales_data s on e.employee_id =s.employee_id 
Group by e.employee_id , e.employee_name
Order by Count(s.employee_id) desc limit 1 ;

			#Expiry Management: Identify all products in the Products table that will expire within the next 90 days
select product_id,product_name from products 
where expiry_date between CURDATE() AND DATE_ADD(CURDATE(), INTERVAL 90 DAY);
 
			# Basket Analysis: What is the average number of items sold per transaction (Average Quantity)?
select avg(quantity)as avg_numb_sold_per_transaction from sales_data ;
  
			# Store Comparisons: Show a list of all stores and the total number of unique products they currently have in their Stock.
select s.store_id,st.store_name ,count(distinct s.product_id) as product
from stock_data s 
inner join stores_data st on s.store_id =st.store_id
group by s.store_id,st.store_name ;

			#Profitability: List the top 5 most profitable products based on the margin between unit_price and cost_price.
select product_id, product_name,(unit_price - cost_price) AS margin
from products
order by margin DESC LIMIT 5;

			# Customer Behavior: What is the most preferred payment_method (Cash, Credit Card, etc.) across all stores?
select  payment_method, count(*) as most_preferred_payment_method
 from sales_data
 group by payment_method
 order by most_preferred_payment_method desc LIMIT 1; ;
 
			# Restock Tracking: Which store has the oldest last_restock_date in the system?
 select store_id , min(last_restocked) as last_restock 
 from stock_data  
 group by store_id
 order by last_restock  asc limit 1 ;
 
			# Discount Impact: Calculate the total amount of money "lost" to discounts across the entire database
select * from sales_data ;
select sum(discount) as total_money_lost 
from sales_data ;

			# Staffing Data: Calculate the average salary of employees per role (Pharmacist vs. Store Manager).
 select position ,avg(salary) as avg_salary 
 from employees
 where position in ('Store Manager' ,'Pharmacist')
group by position ;

			# Brand Popularity: Which brand (e.g., Pfizer, Bayer) has the highest total quantity sold?
select p.brand ,sum(s.quantity) as total_quantity
from products p 
inner join sales_data s on p.product_id=s.product_id
group by p.brand 
order by  total_quantity desc limit 1;

			# Daily Trends: On which day of the week do the stores experience the highest volume of sales?
select count(*) AS total_sales ,  dayofweek(sale_date) as highest_sales_day
from sales_data
group by highest_sales_day
order by total_sales desc limit 1 ;   

            #Inventory Valuation: What is the total value of the current stock in the Wellness Hub store (using cost_price * stock_level)?
select st.store_id,st.store_name, SUM(p.cost_price * s.quantity) as total_value_of_current_stock
from stock_data s
inner join  stores_data st on s.store_id = st.store_id
inner join products p on s.product_id = p.product_id
where st.store_name = 'Wellness Corner'
group by  st.store_id, st.store_name;
